name: dio_internet_interceptor
description: dio interceptor
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0
dependencies:
  dio: ^5.4.3+1
  hive: ^2.2.3
  internet_connection_checker: ^2.0.0
  path_provider: ^2.1.3
